# -*- coding: utf-8 -*-
"""preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMHu3ppBaJrkmOxW6OyEya_qPuzey4Jd
"""

import os
import cv2
import random
import shutil
from pathlib import Path

# ==============================================================================
# CONFIGURATION SETUP
# ==============================================================================
# Define raw input source folder and processed output target folder names
RAW_INPUT_DIR = "raw_videos"
PROCESSED_OUTPUT_DIR = "processed_dataset"

# Define the exact state categories your model will learn to predict
CLASSES = ["running",  "stopped"]

# Set dataset separation parameters (80% for training, 20% for testing validation)
SPLIT_RATIO = 0.8

# Frame sampling step: Keep 1 frame out of every 5 frames to extract temporal
# motion cues without saving hundreds of nearly identical, redundant images.
FRAME_EXTRACT_INTERVAL = 5

# Target output resolution for YOLO classification model inputs (square format)
TARGET_IMAGE_SIZE = (224, 224)


def setup_directory_structure():
    """
    Initializes and verifies the local folder layouts on your machine.
    Creates both the raw intake paths and the structured training splits.
    """
    print("--------------------------------------------------")
    print("📁 [1/4] INITIALIZING FACTORY DIRECTORY STRUCTURE")
    print("--------------------------------------------------")

    # 1. Create intake folders for user's sample video source files
    for state_class in CLASSES:
        intake_path = os.path.join(RAW_INPUT_DIR, state_class)
        if not os.path.exists(intake_path):
            os.makedirs(intake_path, exist_ok=True)
            print(f"Created initial source folder: {intake_path}")

    # 2. Create target validation split architecture folders for YOLO processing
    for split_subset in ["train", "val"]:
        for state_class in CLASSES:
            split_path = os.path.join(PROCESSED_OUTPUT_DIR, split_subset, state_class)
            os.makedirs(split_path, exist_ok=True)

    print("✔ All folder paths mapped successfully.")


def extract_and_split_frames():
    """
    Loops through the user's video files, processes individual frames via OpenCV,
    resizes images, shuffles the distribution, and saves them to disk.
    """
    print("\n--------------------------------------------------")
    print("🎬 [2/4] PROCESSING VIDEO SOURCE FILE STREAMS")
    print("--------------------------------------------------")

    # Supported extension tracking
    valid_extensions = ('.mp4', '.avi', '.mov', '.mkv', '.webm')

    for state_class in CLASSES:
        source_class_path = os.path.join(RAW_INPUT_DIR, state_class)
        video_files = [f for f in os.listdir(source_class_path) if f.lower().endswith(valid_extensions)]

        if not video_files:
            print(f"⚠️ Class '{state_class}': No source videos found in '{source_class_path}'.")
            print(f"   --> Action: Drop your sample video clips into that folder and re-run.")
            continue

        print(f"Processing {len(video_files)} file(s) inside category: [{state_class.upper()}]")
        extracted_image_paths = []

        # Parse every video assigned to this category state
        for video_filename in video_files:
            full_video_path = os.path.join(source_class_path, video_filename)
            video_capture = cv2.VideoCapture(full_video_path)

            # Extract basic file name without format trailer extension
            base_name = Path(video_filename).stem
            global_frame_idx = 0
            saved_frame_counter = 0

            while True:
                success, current_frame = video_capture.read()
                if not success:
                    break # Reached terminal frame end or stream error

                # Evaluate sampling frequency guardrail step
                if global_frame_idx % FRAME_EXTRACT_INTERVAL == 0:
                    # Clean geometric scaling transform down to model shape metrics
                    processed_frame = cv2.resize(current_frame, TARGET_IMAGE_SIZE)

                    # Generate explicit clean file name signature string
                    output_img_name = f"{base_name}_frame_{global_frame_idx:06d}.jpg"
                    temporary_output_path = os.path.join(PROCESSED_OUTPUT_DIR, output_img_name)

                    # Temporarily commit frame to file root array before shuffling distribution
                    cv2.imwrite(temporary_output_path, processed_frame)
                    extracted_image_paths.append(temporary_output_path)
                    saved_frame_counter += 1

                global_frame_idx += 1

            video_capture.release()
            print(f"  └─ Finished processing video: {video_filename} (Extracted {saved_frame_counter} sample images)")

        # ----------------------------------------------------------------------
        # DATA DISTRIBUTION SHUFFLING & DIVISION STEPS
        # ----------------------------------------------------------------------
        if extracted_image_paths:
            print(f"🎲 [3/4] Shuffling and dividing data distribution lists for '{state_class}'...")

            # Randomize tracking indexes entirely to break linear video progression bias
            random.shuffle(extracted_image_paths)

            # Find point where data splits into 80% chunks
            separation_threshold = int(len(extracted_image_paths) * SPLIT_RATIO)

            training_allocation_list = extracted_image_paths[:separation_threshold]
            validation_allocation_list = extracted_image_paths[separation_threshold:]

            # Routinely move individual frame items to targeted directory architecture
            print(f"🚚 [4/4] Routing files to permanent dataset splits...")

            for file_path in training_allocation_list:
                destination = os.path.join(PROCESSED_OUTPUT_DIR, "train", state_class, os.path.basename(file_path))
                shutil.move(file_path, destination)

            for file_path in validation_allocation_list:
                destination = os.path.join(PROCESSED_OUTPUT_DIR, "val", state_class, os.path.basename(file_path))
                shutil.move(file_path, destination)

            print(f"✨ Category [{state_class.upper()}] Done! Created: {len(training_allocation_list)} train, {len(validation_allocation_list)} validation frames.\n")


if __name__ == "__main__":
    # Ensure random sequence seed stays repeatable if debug checks are run
    random.seed(42)

    print("==================================================")
    print("🏭 LOCAL DATA PREPROCESSING LIFECYCLE INITIALIZED")
    print("==================================================")

    setup_directory_structure()
    extract_and_split_frames()

    print("==================================================")
    print("🎉 PIPELINE COMPLETED")
    print("==================================================")
    print(f"Next Action: Verify directories in your local project root folder '{PROCESSED_OUTPUT_DIR}'")
    print("You are now fully prepared to run your 'train.py' model pipeline.")