# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMHu3ppBaJrkmOxW6OyEya_qPuzey4Jd
"""

import os
from ultralytics import YOLO

def main():
    # 1. Load a pre-trained ultra-fast classification model base
    # 'yolov8n-cls.pt' is tiny, fast, and perfect for running locally
    model = YOLO("yolov8n-cls.pt")

    print("--------------------------------------------------")
    print("🚀 INITIALIZING LOCAL AI MODEL TRAINING (2 CLASSES)")
    print("--------------------------------------------------")

    # 2. Train the model on your processed local dataset
    results = model.train(
        data="processed_dataset",   # Points to your train/val folders
        epochs=20,                  # How many times the AI reviews the dataset (change to 30 if you have time)
        imgsz=224,                  # Image size matching your preprocessing script
        device="0" if model.device == "cuda" else "cpu",  # Auto-uses NVIDIA GPU if available
        workers=2,                  # Number of CPU threads to handle data loading
        project="factory_runs",     # Folder where training progress is saved
        name="roller_classifier"    # Subfolder name for this specific run
    )

    print("--------------------------------------------------")
    print("🎉 TRAINING SUCCESSFUL!")
    print("Your trained model is saved at:")
    print("factory_runs/roller_classifier/weights/best.pt")
    print("--------------------------------------------------")

if __name__ == "__main__":
    main()



