# # -*- coding: utf-8 -*-
# """verify_model

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1eMHu3ppBaJrkmOxW6OyEya_qPuzey4Jd
# """

import cv2
from ultralytics import YOLO

# 1. Path to your best trained model weights
MODEL_PATH = r"D:\projct_demo\factory_analytics\runs\classify\factory_runs\roller_classifier\weights\best.pt"
model = YOLO(MODEL_PATH)

# 2. Path to a sample video file to test with
# (Pick a file you didn't use in training, or use one of your raw clips to verify)
TEST_VIDEO = r"D:\projct_demo\Trash\WhatsApp Video 2026-08-11 at 8.19.39 PM.mp4"
cap = cv2.VideoCapture(TEST_VIDEO)

print("Opening Verification Window. Press 'q' to close.")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # 3. Predict the frame state
    results = model(frame, verbose=False)

    for r in results:
        # Extract top prediction and confidence metrics
        class_id = r.probs.top1
        class_name = r.names[class_id]
        confidence = float(r.probs.top1conf) * 100

        # UI Color feedback assignment
        color = (0, 255, 0) if class_name == "running" else (0, 0, 255)

        # 4. Draw UI box and overlay status text onto frame
        cv2.rectangle(frame, (15, 15), (420, 110), (0, 0, 0), -1) # Dark label background box
        cv2.putText(frame, f"STATE: {class_name.upper()}", (30, 55),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, color, 3)
        cv2.putText(frame, f"Confidence: {confidence:.1f}%", (30, 90),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

    # 5. Render window frame
    cv2.imshow("Model Quality Verification", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
print("Verification complete.")



